name: rideapp
description: A ride-sharing app for South Africa
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ">=3.6.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  # firebase_analytics:  # Removed due to Kotlin compatibility issues
  google_maps_flutter:
  geolocator:
  geocoding:
  google_places_flutter:
  image_picker:
  cloudinary_flutter:
  mime:
  file_picker:
  provider:
  flutter_polyline_points:
  intl:
  http:
  shared_preferences:
  flutter_spinkit:
  google_fonts:
  flutter_svg:
  url_launcher:
  flutter_rating_bar:
  cached_network_image:
  lottie:
  google_maps_webservice:
  paystack_for_flutter:
  flutter_map:
  latlong2:
  smooth_page_indicator:
  timeago:
  audioplayers:
  connectivity_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

dependency_overrides:
  webview_flutter: ^4.2.4
  webview_flutter_android: ^3.8.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - shorebird.yaml
  #   - assets/animations/

